# -*- coding: utf-8 -*-
"""CurrencyChange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QO5axW58CpFK0nBSUjm-WJreDFv3QUZn
"""

import requests as rq
from bs4 import BeautifulSoup as bs



url = "https://www.xe.com/currencytables/?from=TZS&date=2023-12-13#table-section"
req = rq.get(url).content

res = bs(req, "html.parser")
rest = res.find("table", class_="currencytables__Table-sc-xlq26m-3 khkgVm")
redd = rest.find('thead').find("tr")
trr = []
for i in redd:
  print(i.text)
  trr.append(i.text)

trr

import pandas as pd

df = pd.DataFrame(columns=trr)
df

redd = rest.find('tbody').find_all("tr")
for it in redd:
  print(it.find("th").text)
  for i in it.find_all("td"):
    print(i.text)

redd = rest.find('tbody').find_all("tr")
tabHd = []

for it in redd:
  newInfo = []
  head = it.find("th").text
  newInfo.append(head)
  newData = [i.text for i in it.find_all("td")]
  for i in newData:
    newInfo.append(i)
  length = len(df)
  # print(head)
  # print(newData)
  # print(newInfo)
  df.loc[length] = newInfo
df
